name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        with-fastapi-version: ["--with fastapi==0.126.0", "--with fastapi==0.132.0", ""]
        include:
          - os: macos-latest
            python-version: "3.14"
            with-fastapi-version: ""
          - os: windows-latest
            python-version: "3.14"
            with-fastapi-version: ""
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      
      - run: uv sync --locked --all-extras --dev
      - run: uv run ruff check .
      - run: uv run ruff format --check .
      
      - name: Show resolved FastAPI version
        run: >
          uv run ${{ matrix.with-fastapi-version }}
          python -c "import fastapi; print(f'FastAPI version: {fastapi.__version__}')"
      
      - name: Run tests
        run: uv run ${{ matrix.with-fastapi-version }} pytest
